### PR TITLE
#70 fix bug preventing large floats from being displayed

### LINKED ISSUE #70: `showtable` gives `InexactError: trunc(Int128, 1.0e100)`
I have a DataFrame read from a CSV that is apparently completely valid (i.e., the CSV is read and transformed to a DataFrame without any error, and I can see its columns by other means). But calling `showtable` on it triggers an `InexactError: trunc(Int128, 1.0e100)` exception.

The stacktrace follows:

```
InexactError: trunc(Int128, 1.0e100)

Stacktrace:
 [1] trunc at ./float.jl:703 [inlined]
 [2] (::TableView.var"#10#11"{JSON.Serializations.StandardSerialization,JSON.Writer.CompactContext{Base.GenericIOBuffer{Array{UInt8,1}}}})(::Float64, ::Int64, ::Symbol) at /home/henrique/.julia/packages/TableView/KmU8j/src/TableView.jl:276
 [3] eachcolumn at /home/henrique/.julia/packages/Tables/UxLRG/src/utils.jl:70 [inlined]
 [4] table2json(::Tables.Schema{(:formulation, :instance_name, :rotation, :filename, :filepath, :solver, :relax, :solver_time_limit, :solver_threads, :termination_status, :raw_status, :primal_status, :dual_status, :simplex_iterations, :barrier_iterations, :number_of_variables, :number_of_constraints, :objective_bound, :objective_value, :dual_objective_value, :solve_time, :node_count, :relative_gap, :exception_detected),Tuple{String,String,Int64,String,String,String,Int64,Float64,Float64,String,String,String,String,Float64,Float64,Int64,Int64,Float64,Float64,Float64,Float64,Float64,Float64,Bool}}, ::DataFrames.DataFrameRows{DataFrame}, ::NTuple{24,DataType}; requested::Nothing) at /home/henrique/.julia/packages/TableView/KmU8j/src/TableView.jl:275
 [5] table2json at /home/henrique/.julia/packages/TableView/KmU8j/src/TableView.jl:264 [inlined]
 [6] _showtable_sync!(::Scope, ::Tables.Schema{(:formulation, :instance_name, :rotation, :filename, :filepath, :solver, :relax, :solver_time_limit, :solver_threads, :termination_status, :raw_status, :primal_status, :dual_status, :simplex_iterations, :barrier_iterations, :number_of_variables, :number_of_constraints, :objective_bound, :objective_value, :dual_objective_value, :solve_time, :node_count, :relative_gap, :exception_detected),Tuple{String,String,Int64,String,String,String,Int64,Float64,Float64,String,String,String,String,Float64,Float64,Int64,Int64,Float64,Float64,Float64,Float64,Float64,Float64,Bool}}, ::NTuple{24,Symbol}, ::NTuple{24,DataType}, ::DataFrames.DataFrameRows{DataFrame}, ::Array{Dict{Symbol,Any},1}, ::Int64, ::String, ::Dict{Symbol,Any}) at /home/henrique/.julia/packages/TableView/KmU8j/src/TableView.jl:202
 [7] showtable(::DataFrame, ::Dict{Symbol,Any}; dark::Bool, title::String, height::Symbol, width::String, cell_changed::Nothing) at /home/henrique/.julia/packages/TableView/KmU8j/src/TableView.jl:196
 [8] showtable at /home/henrique/.julia/packages/TableView/KmU8j/src/TableView.jl:71 [inlined] (repeats 2 times)
 [9] top-level scope at In[9]:6
 [10] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```

The problem seem to arise because a column has some very large values? I would guess this bug was introduced by this recent commit: https://github.com/baumgold/TableView.jl/commit/5dd10f6e8793bdee8f6b073b1b41d196f1983b8d but I am not sure if it is the exact line that appears in the stacktrace.

### PR DESCRIPTION
**Pull request by baumgold**
Fixes #70

### CODE REVIEW

File: src/TableView.jl [hunk 1]
```diff
@@ -259,6 +258,14 @@ function _showtable_async!(w, schema, names, types, rows, coldefs, tablelength,
     onimport(w, handler)
 end
 
+function _is_javascript_safe(x::Integer)
+    -Int128(2^53)-1 < x < Int128(2^53)-1
+end
+
+function _is_javascript_safe(x::AbstractFloat)
+    -2^53-1 < x < 2^53-1
```
Comment (pfitzseb) [inline src/TableView.jl:266]: I think this needs to be `Int64(2)^53` because int literals on 32-bit systems are `Int32`, which overflows here (same above).

**Review by pfitzseb — CHANGES_REQUESTED** [review]

File: src/TableView.jl (hunk 1 above)
Comment (baumgold) [reply src/TableView.jl:266]: Indeed, good catch - thanks!  Fixed in the most recent commit.

**Review by pfitzseb — APPROVED** [review]
Thanks!
